Django./blog/urls.py
from django.urls import path
from . import views
# from blog.views import Index

app_name = 'blog'

urlpatterns = [
    #path(패턴, 맵핑) /blog/
    # path("", views.index), #index 페이지를 의미함 /FBV 방법 
    # path("", Index.as_view()) # CBV 방법
    # 글 목록 조회
    path("", views.List.as_view(), name='list'), #/blog/
    # 글 상세 조회
    path("detail/<int:pk>/", views.DetailView.as_view(), name='detail'), # /blog/detail/1
    #글 작성
    path("write/", views.Write.as_view(), name='write'), #/blog/write/
    #글 수정
    path("detail/<int:pk>/edit/", views.Update.as_view(), name='edit'),
    #글 삭제
    path("detail/<int:pk>/delete/", views.Delete.as_view(), name='delete'),
    #코멘트 작성
    path("detail/<int:pk>/comment/write", views.CommentWrite.as_view(), name='cm-write'),
    #코멘트 삭제
    path("detail/comment/<int:pk>/delete/", views.CommentDelete.as_view(), name='cm-delete'),
    # 태그 작성
    path("detail/<int:pk>/hashtag/write/", views.HashTagWrite.as_view(), name='tag-write'),
    # 태그 삭제
    path("detail/<int:pk>/hashtag/delete/", views.HashTagDelete.as_view(), name='tag-delete'),
]

Django./blog/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    writer = models.CharField(max_length=10)
    created_at = models.DateTimeField(auto_now_add=True) #수정 되었을 때 시간 변경이 안 되도록 하는 것 
    updated_at = models.DateTimeField(auto_now=True)


class Comment(models.Model):
    post = models.ForeignKey('Post', on_delete=models.CASCADE) #내가 참조할 포스트가 무엇인가?
    content = models.TextField()
    writer = models.CharField(max_length=10)
    created_at = models.DateTimeField(auto_now_add=True) #수정 되었을 때 시간 변경이 안 되도록 하는 것 

    # 보여지는 제목들을 __str__에 맞춰서 하겠다
    def __str__(self):
        return f'Comment on {self.post.title}'


class HashTag(models.Model):
    post = models.ForeignKey('Post', on_delete=models.CASCADE)
    # 관계형 데이터 베이스 with Post table
    name = models.CharField(max_length=10)

    def __str__(self):
        return self.name
        # 태그명만 가져오게 하는 것 

Django./blog/forms.py
# blog/forms.py
from django import forms
from .models import Post, Comment, HashTag

# Form 일반 작성 법 () : html에 있는 form 태그
# Model Form 작성 법 [] : model 을 사용하는 form
# Form  작성은 사용자 입력 값에 대한 유효성 검사를 위한 것
# 유효성 검사를 왜 할까? 클라이언트가 보내는 값이 안전한지 보는 것 
# 프론트와 백엔드 단에서 한 번 막아줌 장고에서는 Forms 라는 파일을 통해서 한 번에 편리하게 유효성 검사
class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['title', 'content'] #form 어떤 걸 제공할꺼야?
    

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['content']
        # widgets 화면출력과 관련된 것 
        widgets = {
            'content': forms.Textarea(attrs={'rows' : '3', 'cols' : '50'})
        }
        #attrs 속성 값 주는 것 : 속성은 html 속성 값을 줄 수 있다.


class HashTagForm(forms.ModelForm):
    
    class Meta:
        model = HashTag
        fields = ['name']

Django./blog/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views import View
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from .models import Post, Comment, HashTag
from .forms import PostForm, CommentForm, HashTagForm
from django.urls import reverse_lazy, reverse

# Create your views here.
# contents list 
# def index(request):
#     if request.method == 'GET': # 요청의 method 구분해주기
        # return HttpResponse('Index page GET')
    # 나머지 요청
    # 나머지 요청이 들어오면, 에러 혹은 예외처리 해줘야함. 
    # return HttpResponse('No!!!')

### Post
class Index(View):
    def get(self, request): # get으로 추출해줘
        # return HttpResponse('Index page Get class')

        # 데이터베이스에 접근해서 값을 가져와야 합니다 (게시글들 목록)
        # 게시판의 글들을 보여줘야하기 때문에 데이터베이스에서 값 조회 기능 사용해야함
        # MyModel.objects.all()
        post_objs = Post.objects.all()
        # context = 데이터베이스에서 가져온 값
        context = {
            "posts" : post_objs #None 하게 되면 다른 화면 실시됨
        }
        # print(post_objs) -> 콘솔에서 확인용
        return render(request, 'blog/board.html', context)

# write
# post -form
# 글 작성 화면 
# def write(request):
#     if request.method == 'POST':
#         # form 확인하는 작업 필요 
#         form = PostForm(request.POST) 
#         if form.is_valid():
#             post = form.save()
#             return redirect('blog:list') #제출 버튼 눌렀을 때 메인페이지로 넘겨줭
#         # Get 일 때
#     form = PostForm() # 새롭게 폼을 제공해준다.
#     return render(request, 'blog/write.html', {'form': form})

# Django 자체의 클래스 뷰 기능도 강력, 편리

# model, template_name, context_object_name,
# paginate_by : 페이지를 어떻게 해줄꺼야? 한 페이지에 글을 몇 개로 해줄꺼야? 와 같은 것 
# form_class, form_valid() -> form 확인 , get_queryset()

# django.views.generic -> ListView
# class List(ListView):
#     model = Post
#     context_object_name = 'blog/write.html'
class List(ListView):
    model = Post
    template_name = 'blog/post_list.html' # 어떤 템플릿 써?
    context_object_name = 'posts' # 어떤 변수 써?


class Write(CreateView):
    model = Post # 모델 
    form_class = PostForm # 어떤 폼을 사용할꺼야?
    success_url = reverse_lazy('blog:list') # 위에 것이 성공하면 보내줄 url


class Detail(DetailView):
    model = Post
    template_name = 'blog/post_detail.html'
    context_object_name = 'post' # 하나만 넘기니깐 변수 이름을 post 로 함


class Update(UpdateView):
    model = Post
    template_name = 'blog/post_edit.html' #수정은 템플릿을  만드는  것이  좋음
    fields = ['title', 'content'] # 사용자가 적을 수 있는 것
    # success_url = reverse_lazy('blog:list')
    # intial 기능 : 초기값 설정 가능하게 해주는 기능 -> form 안에 값을 미리 넣어주기 위해서 작업

    def get_initial(self):
        initial = super().get_initial() #updateview 의 intial 가져옴
        post = self.get_object() # pk 기반으로 객체 가져옴
        initial['title'] = post.title
        initial['content'] = post.content # 값 추가
        return initial
    
    def get_success_url(self): 
        post = self.get_object() # pk 기반으로 현재 객체 가져오기 
        return reverse('blog:detail', kwargs={'pk': post.pk})
    
    #get_absolute_url


class Delete(DeleteView):
    model = Post
    success_url = reverse_lazy('blog:list')


class DetailView(View):
    def get(self, request, pk): # pk: 데이터베이스 post_id 테이블 이름 사용하고 싶어서
        # 데이터베이스 방문
        # 해당 글 하나 가져옴
        # 장고 ORM (pk -> 변경불가한 이름)
        post = Post.objects.get(pk=pk)
        # 글에 해당하는 댓글 가져옴 (comment에서 렌더링할 때  댓글 자체가 있어야하니깐)
        comments = Comment.objects.filter(post=post) #외래키와 연결
        #해시태그
        hashtags = HashTag.objects.filter(post=post)

        # 댓글 form (입력칸)
        comment_form = CommentForm()

        #태그 form (입력칸)
        hashtag_form = HashTagForm()
        context = {
            'post': post,
            'comments': comments,
            'hashtags': hashtags,
            'comment_form': comment_form,
            'hashtag_form': hashtag_form,
        }
        return render(request, 'blog/post_detail.html', context)


### Comment
class CommentWrite(View):
    # def get(self, request):
    #     pass
    def post(self, request, pk):
        form = CommentForm(request.POST)
        if form.is_valid():
            # 사용자에게 댓글 내용을 받아옴
            content = form.cleaned_data['content']
            # cleande_data : 정확하게 원하는 값 content 를 가져옴 ; 폼의 특정 값을 가져오고 싶을 때 사용 
            # 해당 아이디에 해당하는 글 불러옴
            post = Post.objects.get(pk=pk)
            # 댓글 객체 생성을 위해 위의 코드 실시 
            comment = Comment.objects.create(post=post, content=content)
            return redirect('blog:detail', pk=pk)
            # comment = Comment(post=post) -> comment.save()
            # redirect 는 그저 화면만 이동


class CommentDelete(View):
    def post(self, request, pk):
        # 지울 객체를 찾아야해요 -> 댓글 객체를 가지고 와야함 -> 댓글 pk
        comment = Comment.objects.get(pk=pk)
        # 삭제 후 상세 페이지로 돌아가기
        post_id = comment.post.id # post = post 객체
        # 삭제
        comment.delete()
        return redirect('blog:detail', pk=post_id)


###Hashtag
class HashTagWrite(View):
    def post(self, request, pk):
        form = HashTagForm(request.POST)
        if form.is_valid():
            # 사용자에게 태그 내용을 받아옴
            name = form.cleaned_data['name']
            # 해당 아이디에 해당하는 글 불러옴
            post = Post.objects.get(pk=pk)
            # 댓글 객체 생성, create 메서드를 사용할 때는 save 필요 없음
            hashtag = HashTag.objects.create(post=post, name=name)
            # comment = Comment(post=post) -> comment.save()
            return redirect('blog:detail', pk=pk)
            # redirect 는 그저 화면만 이동


class HashTagDelete(View):
    def post(self, request, pk):
        # 지울 객체를 찾아야 한다. -> 태그 객체
        hashtag = HashTag.objects.get(pk=pk)
        # 상세페이지로 돌아가기
        post_id = hashtag.post.id
        # 삭제
        hashtag.delete()
        
        return redirect('blog:detail', pk=post_id)

Django./blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <title>블로그</title>
  </head>
  <body>
    <div class="container">
      <h1>Blog</h1>
      {% block content %} 
      {% endblock %}
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>

  </body>
</html>

Django./blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
<h2>제목 : {{ post.title }}</h2>
<p>내용 : {{ post.content }}</p>
<a href="{% url 'blog:edit' pk=post.pk %}" class="btn">수정</a>
<form action="{% url 'blog:delete' pk=post.pk %}" method="post">
    {% csrf_token %}
    <input type="submit" value="삭제" class="btn">
</form>
<p>작성자 : {{ post.writer }}</p>
<p>작성일 : {{ post.created_at }}</p>
<hr>
<!-- comment 작성 화면 -->
<h3>댓글</h3>
<form action="{% url 'blog:cm-write' pk=post.pk %}" method="post">
    {% csrf_token %}
    {{ comment_form.content }} <!-- label-tag 넣으면 'content' 가 보임 -->
    <input type="submit" value="댓글 작성" class="btn">
</form>
<br>
<!-- comments -->
<!-- if : 댓글이 없을 수 있기 때문에  -->
{% if comments %}
    <!-- for : 여러개의 댓글이 있기 때문에 -->
    
    <ul>
        {% for comment in comments%}
        <!-- 댓글 내용, 작성 시간, 삭제 버튼 -->
            <li>{{ comment.content }} / {{ comment.created_at }}
                <form action="{% url 'blog:cm-delete' pk=comment.pk %}" method="post">
                    {% csrf_token %}
                        <input type="submit" value="X" class="btn btn-outline-success">
                </form>
            </li>
            
        {% endfor %}
    </ul>
{% else %}
    <p>댓글이 없습니다.</p>
{% endif %}
<hr>
<!-- 태그작성 화면 -->
<h3>해시태그</h3>
<form action="{% url 'blog:tag-write' pk=post.pk %}" method="post">
    {% csrf_token %}
    {{ hashtag_form.name }}
    <input type="submit" value="태그 작성">
</form>
{% if hashtags %}
<ul>
    {% for hashtag in hashtags %}
    <li>
        {{ hashtag }}
        <form action="{% url 'blog:tag-delete' pk=hashtag.pk %}" method="post">
            {% csrf_token %}
            <input type="submit" value="X" class='btn'>
        </form>
    </li>
    {% endfor %}
</ul>
{% else %}
<br>
<p>해시태그가 없습니다.</p>
{% endif %}

{% endblock %}

Django./blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.title.label_tag }}
    <input type="text" name="{{ form.title.name }}" value="{{ form.initial.title }}">
    <br>
    {{ form.content.label_tag }}
    <textarea type="text" name="{{ form.content.name }}">{{ form.initial.content }}</textarea>
    <br>
    <input type="submit">
</form>
{% endblock %}

Django./blog/templates/blog/post_form.html
<!-- blog/write.html -->
{% extends 'blog/base.html' %}

{% block content %}
    <p>블로그 글 작성 화면</p>
    <!-- 제목 -->
    <!-- 내용 -->

    <form action="{% url 'blog:write' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="bnt btn-outline-success">
    </form>
{% endblock %}

Django./blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}
{% block content %}
    <p>블로그 게시판 첫 화면입니다.</p>
    <a href="{% url 'blog:write' %}" class="btn btn-outline-success">글 작성</a>
    <!-- 글이 있을 때 테이블 -->
    {% if posts %}
        <table class="table table-bordered">
            <thead class="table-light">
                <tr>
                    <td>Title</td>
                    <td>Content</td>
                    <td>Writer</td>
                </tr>
            </thead>
            <tbody>
                {% for post in posts %}
                    <tr>
                        <td><a href="{% url 'blog:detail' pk=post.pk %}" calss="btn">{{ post.title }}</a></td>
                        {#<td>{{ post.content }}</td>#}
                        <td>{{ post.writer }}</td>
                    </tr>
                {% endfor %} 
            </tbody>
        </table>
    {% else %}
        <!-- 글이 없을 때 문구 출력 -->
        <p>작성된 게시물이 없습니다.</p>
    {% endif %}
{% endblock%}